name = "my-cloudinary-uploader"
main = "src/index.ts"
compatibility_date = "2025-05-12"

[vars]
CLOUDINARY_CLOUD_NAME = "dims0c6bk"
CLOUDINARY_API_KEY = "116137818689639"
CLOUDINARY_API_SECRET = "CQbxkDN47pPzvHAQCRylsTC_ZY0"
UPLOAD_PRESET = "my_unsigned_preset" # 記得換成你的 Unsigned Preset 名稱

[build]
command = "npm run build"

[env.dev]
vars = { 
  CLOUDINARY_CLOUD_NAME = "dims0c6bk",
  CLOUDINARY_API_KEY = "116137818689639",
  CLOUDINARY_API_SECRET = "CQbxkDN47pPzvHAQCRylsTC_ZY0",
  UPLOAD_PRESET = "my_unsigned_preset"
}
